export type StoryFilm = { id: string; title: string; description: string; publisher: string };

/** IDs verified against the official publishers' YouTube oEmbed records, 9 Sep 2026. */
export const STORY_FILMS: Record<'lapig' | 'fica', StoryFilm[]> = {
  lapig: [
    { id: 'INiMdP37z-E', title: 'Thirty years of LAPIG', description: 'The laboratory’s own anniversary film, with English subtitles.', publisher: 'LAPIG UFG' },
    { id: 'ejSyEkKsdyU', title: 'Native vegetation, seen in the field', description: 'Middle Tocantins, Paranã and Terra Ronca, in the Atlas of Goiás’s Remaining Vegetation series.', publisher: 'LAPIG UFG' },
    { id: 'nihnic0in_o', title: 'Learning with geotechnologies', description: 'TV UFG introduces Geocursos, LAPIG’s training programme.', publisher: 'TV UFG' },
  ],
  fica: [
    { id: 'sLEmYh5ZHgg', title: 'Inside FICA 2026', description: 'TV UFG’s report on the closing of the 2026 festival and its celebration of Goiás’s culture.', publisher: 'TV UFG' },
    { id: 'bJ_SweXv_Jw', title: 'Cinema powered by bicycles', description: 'BikeCine connects a film screening with energy generated by the audience.', publisher: 'TV UFG' },
    { id: 'HTiwPVGIXDw', title: 'Cinema in schools', description: 'A report on the festival’s filmmaking workshops in schools.', publisher: 'TV UFG' },
  ],
};
